services:
  - type: web
    name: musicgen-service
    env: python
    buildCommand: |
      mkdir -p /opt/render/.cache/huggingface
      pip install -r requirements.txt
      # Pre-download model into the same cache used at runtime
      TRANSFORMERS_CACHE=/opt/render/.cache/huggingface python -c "from transformers import pipeline; pipeline('text-to-audio','facebook/musicgen-small')"
    startCommand: gunicorn app:app --timeout 120 --bind 0.0.0.0:$PORT
