services:
  - type: web
    name: musicgen-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --bind 0.0.0.0:$PORT --worker-class gthread --threads 2
